server:
  address: 0.0.0.0
  port: 8080

spring.jpa.defer-datasource-initialization: true
spring.sql.init.mode: always
spring:
  datasource:
    url: jdbc:mysql://containers-us-west-195.railway.app:7946/railway
    username: root
    password: Iic8kw6YC5XFd2MyGw2d
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true


  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes