spring.jpa.defer-datasource-initialization: true
spring.sql.init.mode: always

spring:
  # konfigurasi untuk koneksi db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    # sesuaikan nama database anda dengan di bawah ini
    url: jdbc:mysql://root:bzXpj7T3whK34FbKbYjR@containers-us-west-47.railway.app:6214/railway
    # sesuaikan dengan NAMA dan PASSWORD anda dengan username password di bawah ini
    username: root
    password: bzXpj7T3whK34FbKbYjR

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

    # pembuatan database (create || create-drop || validate || update)
    hibernate.ddl-auto: create-drop

    show-sql: true
